#!/bin/sh

cat <<EOF >/etc/yum.repos.d/saltstack.repo
[saltstack-repo]
name=SaltStack repo for RHEL/CentOS $releasever
baseurl=https://repo.saltstack.com/yum/redhat/\$releasever/\$basearch/archive/2016.11.5
enabled=1
gpgcheck=1
gpgkey=https://repo.saltstack.com/yum/redhat/\$releasever/\$basearch/archive/2017.7.0/SALTSTACK-GPG-KEY.pub
EOF

yum clean expire-cache
yum -y install salt-minion git

sleep 300

echo 'role:' >>/etc/salt/grains
echo '- salt' >>/etc/salt/grains

mkdir -p /etc/salt/minion.d/
echo 'master: localhost' >/etc/salt/minion.d/master.conf

mkdir /root/src
cd /root/src
git clone https://github.com/nbirnel/sonarqube-demo/
cd sonarqube-demo
ln -s ${PWD}/salt /srv/salt

systemctl enable salt-master
systemctl restart salt-master

systemctl enable salt-minion
systemctl restart salt-minion

sleep 120

salt-call state.highstate | tee /root/highstate
